### ISSUE TITLE
Build fails on Windows machine

### ISSUE THREAD

**Issue by ZenaMel** [Vincenius/static-website-template#13]
Stacktrace:

```
gyp verb command build []
gyp verb build type Release
gyp verb architecture x64
gyp verb node dev dir C:\Users\STUDIUM\.node-gyp\14.15.3
gyp verb found first Solution file build/binding.sln
gyp verb `which` succeeded for `msbuild` C:\Program Files (x86)\MSBuild\14.0\Bin\msbuild.EXE
gyp info spawn msbuild
gyp info spawn args [
gyp info spawn args   'build/binding.sln',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=x64'
gyp info spawn args ]
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
Build started 9/02/2021 11:56:47 PM.
Project "C:\SoftwareDevelopment\Epic-Project-Explorer\ui\static-website-template-master\node_modules\node-sass\build\binding.sln" on node 1 (default targets).
ValidateSolutionConfiguration:
  Building solution configuration "Release|x64".
Project "C:\SoftwareDevelopment\Epic-Project-Explorer\ui\static-website-template-master\node_modules\node-sass\build\binding.sln" (1) is building "C:\SoftwareDevelopment\
Epic-Project-Explorer\ui\static-website-template-master\node_modules\node-sass\build\binding.vcxproj.metaproj" (2) on node 1 (default targets).
Project "C:\SoftwareDevelopment\Epic-Project-Explorer\ui\static-website-template-master\node_modules\node-sass\build\binding.vcxproj.metaproj" (2) is building "C:\Softwar 
eDevelopment\Epic-Project-Explorer\ui\static-website-template-master\node_modules\node-sass\build\src\libsass.vcxproj" (3) on node 1 (default targets).
C:\SoftwareDevelopment\Epic-Project-Explorer\ui\static-website-template-master\node_modules\node-sass\build\src\libsass.vcxproj(21,3): error MSB4019: The imported project 
 "C:\Microsoft.Cpp.Default.props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.
Done Building Project "C:\SoftwareDevelopment\Epic-Project-Explorer\ui\static-website-template-master\node_modules\node-sass\build\src\libsass.vcxproj" (default targets)  
-- FAILED.

Done Building Project "C:\SoftwareDevelopment\Epic-Project-Explorer\ui\static-website-template-master\node_modules\node-sass\build\binding.vcxproj.metaproj" (default targ
ets) -- FAILED.

Done Building Project "C:\SoftwareDevelopment\Epic-Project-Explorer\ui\static-website-template-master\node_modules\node-sass\build\binding.sln" (default targets) -- FAILE 
D.


Build FAILED.

"C:\SoftwareDevelopment\Epic-Project-Explorer\ui\static-website-template-master\node_modules\node-sass\build\binding.sln" (default target) (1) ->
"C:\SoftwareDevelopment\Epic-Project-Explorer\ui\static-website-template-master\node_modules\node-sass\build\binding.vcxproj.metaproj" (default target) (2) ->
"C:\SoftwareDevelopment\Epic-Project-Explorer\ui\static-website-template-master\node_modules\node-sass\build\src\libsass.vcxproj" (default target) (3) ->
  C:\SoftwareDevelopment\Epic-Project-Explorer\ui\static-website-template-master\node_modules\node-sass\build\src\libsass.vcxproj(21,3): error MSB4019: The imported proje 
ct "C:\Microsoft.Cpp.Default.props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.

    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:00.71
gyp ERR! build error 
gyp ERR! stack Error: `msbuild` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\SoftwareDevelopment\Epic-Project-Explorer\ui\static-website-template-master\node_modules\node-gyp\lib\build.js:262:23)       
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
gyp ERR! System Windows_NT 10.0.19041
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\SoftwareDevelopment\\Epic-Project-Explorer\\ui\\static-website-template-master\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd C:\SoftwareDevelopment\Epic-Project-Explorer\ui\static-website-template-master\node_modules\node-sass
gyp ERR! node -v v14.15.3
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
Build failed with error code: 1
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.2 (node_modules\postcss-cli\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.2 (node_modules\onchange\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@4.13.1 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@4.13.1 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by ZenaMel** [comment]
This happens after running `npm i && npm run build`

**Comment by scibuff** [comment]
> This happens after running `npm i && npm run build`

@Zenahr I think you need to manually update the `node-sass` package. The 4.13.1 is too old (might not be available anymore to download). I would actually manually update all used packages
